version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: drucoder/web-server
    ports:
      - 3000-3005:3000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8989:8989







#version: "3"
#services:
#  nginx:
#    image: nginx:latest
#    #links:
#    #  - node
#  node:
#    image: node:latest
#    restart: always
#    links:
#      - nginx




# Если не стоит docker-compose, устанавляваем через brew install docker-compose
# запускаем в папке через docker-compose up -d в фоновом режиме

# docker exec -it t06_nginx_1 /bin/bash
#Нужно апдейтнуть и установить ping (после стопа контейнеров)
# apt update  - апдейтим ping
# apt install iputils-ping
# ping t06_nginx_1 -c 2

# Остановка и Удаление Контейнеров
# docker stop $(docker ps -qa) останавливаем все работающие контейнеры (docker-compose stop $(docker-compose ps -qa)
# docker rm $(docker ps -qa) удаляем контейнеры

# Удаление Образов
# docker rmi $(docker images -q)